#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userdefaults=$HOME/.Xdefaults

#Launch the SSH Agent
eval "$(ssh-agent -s)" &

# merge in default and keymaps

if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
	xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
	xmodmap $usermodmap
fi

if [ -f $userdefaults ]; then
	xrdb -merge $userdefaults
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

#Setup the compositor
picom &


#Setup the desktop wallpaper
./.fehbg &


#load the status bar
dwmstatus 2&>1 >/dev/null &

#load dwm
if [ "$(command -v dwm)" >/dev/null 2>&1 ]; then
	exec dwm
fi

#loop
#while true; do
#	dwm >/dev/null 2>&1
#done
#To get autostsart to run we need to launch openbox-session, NOT openbox on its own
#if [ "$(command -v openbox-session)" >/dev/null 2>&1 ]; then
#	exec openbox-session
#fi
